workspace 1 output $mainMonitor
workspace 2 output $mainMonitor
workspace 3 output $mainMonitor
workspace 4 output $rightMonitor
workspace 5 output $rightMonitor
workspace 6 output $rightMonitor
workspace 7 output $leftMonitor
workspace 8 output $leftMonitor
workspace 9 output $leftMonitor
