# remapping prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# remapping split current window
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# remapping reload
bind r source-file ~/.tmux.conf

# adding keybinds to move between panels without prefix
unbind -n C-h
unbind -n C-l
unbind -n C-k
unbind -n C-j
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

# remapping new window creation
unbind c
unbind Enter
bind-key Enter new-window

# changing the starting number form 0 to 1
set -g base-index 1
set -g pane-base-index 1
